POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
 "name": "rasel hossain",
 "email": "rasel@gmail.com",
 "password": "pass123"
}

###
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
 "email": "rasel@gmail.com",
 "password": "pass123"
}
 
###
POST http://localhost:4000/api/v1/utilities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjQ4MDIzYzgyMzlhN2MwMDgxYzdhOCIsIm5hbWUiOiJyYXNlbCBob3NzYWluIiwiZW1haWwiOiJyYXNlbEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTM3NTU3MjUsImV4cCI6MTY5Mzc1OTMyNX0.gcPrMHs8PBmUDSiHK6fQeRI0CJgAlZ885cTdQDV-NXg


{ 
  "name": "utility created",
  "flatNo": 101,
  "ElectricityBill": 12000,
  "GasBill": 1200,
  "InternetBill": 1000,
  "ServiceCharge":8000
  
}
###
DELETE http://localhost:4000/api/v1/utilities/64f4adcc74e5bce1429472c2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjQ4MDIzYzgyMzlhN2MwMDgxYzdhOCIsIm5hbWUiOiJyYXNlbCBob3NzYWluIiwiZW1haWwiOiJyYXNlbEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTM3NTU3MjUsImV4cCI6MTY5Mzc1OTMyNX0.gcPrMHs8PBmUDSiHK6fQeRI0CJgAlZ885cTdQDV-NXg